
export type Project = {
  id: number;
  slug: string;
  title: string;
  description: string;
  longDescription: string;
  category: 'Web App' | 'Mobile App' | 'AI/ML';
  imageUrl: string;
  technologies?: string[];
  gallery: string[];
  featured: boolean;
  url: string;
  industry: string;
  status: string;
  year: number;
  implementation: string[];
  mobileScreenshots?: string[];
};

export const projects: Project[] = [
  {
    id: 1,
    slug: 'wokine',
    title: 'Wokine',
    description: 'A digital and creative agency with a focus on ethical and creative solutions.',
    longDescription: 'Wokine is a digital and creative agency based in Lille, France, that has been operating since 2004. They specialize in digital strategy, data, e-commerce, and web development, with a focus on combining creativity, technology, and ethical commitment to design digital solutions.',
    category: 'Web App',
    imageUrl: 'https://res.cloudinary.com/cauders/image/upload/v1768691916/wokine-mockup_gfoet8.png',
    technologies: ['Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'Framer Motion'],
    gallery: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683559/gallery-1_jnxpij.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683558/gallery-2_il36js.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683559/gallery-3_w74qpg.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683565/gallery-4_nwcuoe.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683561/gallery-5_wow45k.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683559/gallery-6_p0uoux.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683568/gallery-7_spsjug.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683566/gallery-8_r1ukss.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683560/gallery-9_w4wbcl.png',
    ],
    featured: true,
    url: 'https://www.wokine.com/',
    industry: 'Digital Agency',
    status: 'Live',
    year: 2023,
    implementation: ['UI/UX', 'Development', 'Strategy'],
  },
  {
    id: 2,
    slug: 'fcinq',
    title: 'FCINQ',
    description: 'An award-winning digital agency specializing in "global experiences".',
    longDescription: 'FCINQ is a digital agency with 17 years of experience, specializing in Design & Code, Production & Motion, Social Media, and Branding. The agency has received numerous awards and is known for its creative strength, with a focus on "global experiences."',
    category: 'Web App',
    imageUrl: '/images/portfolio/fcinq.png',
    technologies: ['React', 'GSAP', 'Three.js', 'WebGL', 'Contentful'],
    gallery: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683757/gallery-1_pqaaj2.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683747/gallery-2_ijsx6j.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683744/gallery-3_vjf0xk.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683748/gallery-4_ajtew0.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683745/gallery-5_hrayzd.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683746/gallery-6_dqnmtt.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683751/gallery-7_q7ehvg.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683751/gallery-8_vdudhb.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683752/gallery-9_e1gskt.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683758/gallery-10_jtkwdo.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683753/gallery-11_hcfc66.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683754/gallery-12_t97zde.png', 
    ],
    featured: true,
    url: 'https://www.fcinq.com/',
    industry: 'Creative Agency',
    status: 'Live',
    year: 2022,
    implementation: ['Design', 'Code', 'Motion'],
  },
  {
    id: 3,
    slug: 'tasweerkash',
    title: 'Tasweerkash',
    description: 'A media production company led by a National Award winner.',
    longDescription: 'Tasweerkash is a photography and media production company led by a National Award winner. The company offers services including wedding, event, and portrait photography, as well as photo education. The website features a portfolio and client testimonials.',
    category: 'Web App',
    imageUrl: 'https://res.cloudinary.com/cauders/image/upload/v1768689573/mockup_mk7k2u.png',
    technologies: ['Wordpress', 'PHP', 'jQuery', 'MySQL', 'Elementor'],
    gallery: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683597/gallery-1_nvz19c.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683597/gallery-1_nvz19c.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683594/gallery-3_haxybz.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683608/gallery-4_rzz135.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683603/gallery-5_g3fval.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683594/gallery-6_vindn4.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683595/gallery-7_sgzgcp.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683601/gallery-8_fzunfi.png',
    ],
    featured: false,
    url: 'https://www.tasweerkash.com/',
    industry: 'Photography',
    status: 'Live',
    year: 2021,
    implementation: ['Branding', 'Development'],
  },
  {
    id: 4,
    slug: 'association-of-learning',
    title: 'Association of Learning',
    description: 'An online provider of flexible home learning courses for adults in the UK.',
    longDescription: 'Association of Learning is a UK-based organization offering affordable and flexible home learning courses for adults. They provide a wide range of courses, including A Levels, GCSEs, and Diplomas, with a focus on personalized tutor support.',
    category: 'Web App',
    imageUrl: '/images/portfolio/association-of-learning.png',
    technologies: ['LMS', 'PHP', 'Moodle', 'MySQL', 'JavaScript'],
    gallery: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683859/gallery-9_ly93yy.jpg',
      'https://res.cloudinary.com/cauders/image/upload/v1768683850/gallery-1_auwtmi.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683851/gallery-2_pucqef.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683853/gallery-3_asqpdi.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683853/gallery-4_kpzjs1.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683854/gallery-5_pozspi.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683855/gallery-6_nhwkdo.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683857/gallery-7_dltkxx.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683858/gallery-8_yaljan.png',
    ],
    featured: false,
    url: 'https://associationoflearning.com/about/',
    industry: 'Education',
    status: 'Live',
    year: 2020,
    implementation: ['LMS Integration', 'Development'],
  },
  {
    id: 5,
    slug: 'peveril-podiatry',
    title: 'Peveril Podiatry',
    description: 'A local podiatry clinic providing expert foot and ankle care.',
    longDescription: 'Peveril Podiatry is a local podiatry clinic in the UK that provides assessments, diagnoses, and treatments for various foot and ankle issues. Their services include nail care, skin care, orthotics, and pain management, and they have an experienced team including a podiatric surgeon.',
    category: 'Web App',
    imageUrl: '/images/portfolio/peveril-podiatry.jpg',
    gallery: [
        'https://res.cloudinary.com/cauders/image/upload/v1768683735/gallery-1_cal14e.png',
        'https://res.cloudinary.com/cauders/image/upload/v1768683729/gallery-2_wkoowv.png',
        'https://res.cloudinary.com/cauders/image/upload/v1768683730/gallery-3_xlf6qn.png',
        'https://res.cloudinary.com/cauders/image/upload/v1768683730/gallery-4_x0k9ge.png',
    ],
    featured: false,
    url: 'https://peverilpodiatry.co.uk/',
    industry: 'Healthcare',
    status: 'Live',
    year: 2022,
    implementation: ['Web Design', 'Development'],
  },
  {
    id: 6,
    slug: 'itc-app',
    title: 'IT Centre App',
    description: 'An ERP solution for computer training institutes.',
    longDescription: 'An app that serves as a complete ERP solution for computer training institutes and digital skills academies. It helps simplify daily operations, manage admissions, track attendance, and provide a dashboard for students and staff.',
    category: 'Mobile App',
    imageUrl: 'https://res.cloudinary.com/cauders/image/upload/v1768683742/Group_26_dhqcjc.png',
    technologies: ['React Native', 'Firebase', 'Node.js', 'MongoDB'],
    gallery: [
        'https://res.cloudinary.com/cauders/image/upload/v1768683741/Group_25_qcrhms.png',
        'https://res.cloudinary.com/cauders/image/upload/v1768683737/Group_12_dyziw6.png',
        'https://res.cloudinary.com/cauders/image/upload/v1768683737/Group_13_ro3hic.png',
    ],
    featured: true,
    url: 'https://play.google.com/store/apps/details?id=com.itcentre',
    industry: 'Education Technology',
    status: 'Live',
    year: 2023,
    implementation: ['Mobile Dev', 'Backend', 'UI/UX'],
    mobileScreenshots: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683738/image_24_j0axe5.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683740/image_27_tqybgj.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683740/image_64_m9cgd6.png', 
    ]
  },
  {
    id: 7,
    slug: 'fajira-admin',
    title: 'Fajira Admin',
    description: 'An e-commerce management app for grocery store owners.',
    longDescription: 'A mobile app solution for small businesses and online e-commerce companies in the grocery sector. It allows store owners to manage orders, products, categories, and promotions directly from their phones.',
    category: 'Mobile App',
    imageUrl: 'https://res.cloudinary.com/cauders/image/upload/v1768683780/gallery-5_mk4qjd.webp',
    technologies: ['Flutter', 'Dart', 'Firebase', 'Stripe'],
    gallery: [
        'https://res.cloudinary.com/cauders/image/upload/v1768683779/gallery-4_bywcoy.webp', 
    ],
    featured: false,
    url: 'https://play.google.com/store/apps/details?id=com.grocery.admin',
    industry: 'E-commerce',
    status: 'Live',
    year: 2022,
    implementation: ['Mobile Dev', 'Firebase'],
     mobileScreenshots: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683773/gallery-1_qprxng.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683774/gallery-2_hsiuxu.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683775/gallery-3_sogdh8.png',
    ]
  },
  {
    id: 8,
    slug: 'reachi-kds',
    title: 'Reachi KDS',
    description: 'A Kitchen Display System to streamline restaurant orders.',
    longDescription: 'A digital screen app designed for commercial kitchens to replace paper order tickets. It helps restaurants manage, prioritize, and track customer orders, aiming to make operations more efficient.',
    category: 'Mobile App',
    imageUrl: 'https://res.cloudinary.com/cauders/image/upload/v1768683711/Group_27_x4appk.png',
    technologies: ['Android', 'Kotlin', 'Socket.IO', 'REST APIs'],
    gallery: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683705/Frame_3_r3outf.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683704/image_34_ejf09y.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683707/image_36_fpre5p.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683708/image_37_nqzcvp.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683706/image_38_vnqu9y.png',
    ],
    featured: true,
    url: 'https://play.google.com/store/apps/details?id=com.reachikds',
    industry: 'Restaurant Tech',
    status: 'Live',
    year: 2023,
    implementation: ['Android Dev', 'API'],
    mobileScreenshots: [ 
    ]
  },
  {
    id: 9,
    slug: 'binof-trainer',
    title: 'BINOF Trainer',
    description: 'A demo app for trainers to manage clients and track performance.',
    longDescription: 'A demo app for trainers who use the BINOF system. It provides a platform for trainers to manage their clients, with features for communication, exercise tracking, and performance evaluation.',
    category: 'Mobile App',
    imageUrl: 'https://res.cloudinary.com/cauders/image/upload/v1768686988/Group_29_rrnitu.png',
    technologies: ['React Native', 'GraphQL', 'Apollo Client', 'PostgreSQL'],
    gallery: [ 
        'https://res.cloudinary.com/cauders/image/upload/v1768683840/gallery-8_rovyhf.png',
    ],
    featured: false,
    url: 'https://play.google.com/store/apps/details?id=com.binofapp.trainer',
    industry: 'Fitness',
    status: 'Demo',
    year: 2021,
    implementation: ['Mobile Dev', 'GraphQL'],
    mobileScreenshots: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683845/gallery-1_ntvsyp.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683846/gallery-2_kympkg.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683829/gallery-3_zdjdf7.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683829/gallery-3_zdjdf7.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683831/gallery-5_o8kad3.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683832/gallery-6_qffeex.png', 
    ]
  },
  {
    id: 10,
    slug: 'diamond-gym-trainer',
    title: 'Diamond Gym Trainer',
    description: 'A fitness app for workout routines, progress tracking, and nutritional guidance.',
    longDescription: 'This is a fitness app that serves as a comprehensive companion for individuals aiming for a healthier lifestyle. It includes workout routines, exercise demonstrations, progress tracking, and nutritional guidance.',
    category: 'Mobile App',
    imageUrl: 'https://res.cloudinary.com/cauders/image/upload/v1768683801/diamond-gym-trainer_nyus1w.png',
    technologies: ['React Native', 'Firebase', 'Chart.js', 'Realm'],
    gallery: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683804/gallery-4_ahldsw.png',  
      'https://res.cloudinary.com/cauders/image/upload/v1768683805/gallery-5_fysvld.png', 
    ],
    featured: false,
    url: 'https://play.google.com/store/apps/details?id=com.diamondgymrd.trainer',
    industry: 'Fitness',
    status: 'Live',
    year: 2022,
    implementation: ['Mobile Dev', 'Firebase'],
     mobileScreenshots: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683798/gallery-1_i8iegq.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683800/gallery-2_xq4h8h.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683799/gallery-3_q8ykxb.png', 
    ]
  },
  {
    id: 11,
    slug: 'clipinn',
    title: 'Clipinn',
    description: 'HR software to simplify human resources management.',
    longDescription: 'An HR software designed to simplify human resources management. It offers a range of features, including attendance tracking, task management, employee and lead management, hiring tools, and a payroll system. The platform also includes collaboration tools and a mobile app.',
    category: 'Web App',
    imageUrl: 'https://res.cloudinary.com/cauders/image/upload/v1768683825/Your_paragraph_text_a1xwwt.png',
    technologies: ['React', 'Node.js', 'PostgreSQL', 'Redux', 'AWS'],
    gallery: [ 
      'https://res.cloudinary.com/cauders/image/upload/v1768683812/gallery-1_jevzsk.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683814/gallery-2_gguec1.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683815/gallery-3_g7sp6f.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683817/gallery-4_miqrpq.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683819/gallery-5_hkvwdb.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683820/gallery-6_j9thww.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683821/gallery-7_ippyhj.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683822/gallery-8_vdyvuy.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683823/gallery-9_phdsab.png', 
    ],
    featured: false,
    url: 'https://clipinn.com/',
    industry: 'HR Tech',
    status: 'Live',
    year: 2021,
    implementation: ['Full-stack Dev', 'SaaS'],
  },
  {
    id: 12,
    slug: 'the-kabul-grill',
    title: 'The Kabul Grill',
    description: 'A website for a restaurant, providing menu and catering information.',
    longDescription: 'The website for a restaurant, providing information on its menu, catering services, and location.',
    category: 'Web App',
    imageUrl: '/images/portfolio/kabul-grill.jpg',
    technologies: ['Wordpress', 'PHP', 'MySQL', 'Elementor', 'Google Maps API'],
    gallery: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683590/gallery-1_hyw56g.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683588/gallery-2_bapccq.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683585/gallery-3_vjnsvo.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683591/gallery-4_jmct5c.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683584/gallery-5_umpiv8.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683582/gallery-6_jfvibm.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683581/gallery-7_aax6to.png', 
    ],
    featured: false,
    url: 'https://thekabulgrill.com/',
    industry: 'Restaurant',
    status: 'Live',
    year: 2020,
    implementation: ['Web Design', 'Development'],
  },
  {
    id: 13,
    slug: 'snipbyte',
    title: 'Snipbyte',
    description: 'A platform for free and premium coding templates.',
    longDescription: 'SnipByte is a dynamic platform offering a rich collection of free and premium coding templates tailored for web developers of all levels—from beginners to seasoned pros. Whether you\'re building with React, Next.js, WordPress, PHP, HTML, Tailwind, or JavaScript, SnipByte provides ready-to-use resources to accelerate your workflow and elevate your projects',
    category: 'Web App',
    imageUrl: '/images/portfolio/snipbyte.png',
    technologies: ['React', 'Next.js', 'Vercel', 'TypeScript'],
    gallery: [
      'https://res.cloudinary.com/cauders/image/upload/v1768689573/mockup_mk7k2u.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683621/gallery-2_njwjl0.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683623/gallery-3_poksio.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683623/gallery-3_poksio.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683623/gallery-3_poksio.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683629/gallery-6_mm98oe.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683630/gallery-7_q9ni01.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683632/gallery-8_i4mzqj.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683636/gallery-9_teigvu.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683639/gallery-12_rdcef8.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683638/gallery-10_qgdy5c.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683637/gallery-11_sjo1os.png', 
      'https://res.cloudinary.com/cauders/image/upload/v1768683641/gallery-13_siaomt.png', 
    ],
    featured: false,
    url: 'https://snipbyte.com/',
    industry: 'Technology',
    status: 'Live',
    year: 2023,
    implementation: ['Web Development'],
  },
  {
    id: 14,
    slug: 'fajira-ecommerce',
    title: 'Fajira Ecommerce',
    description: 'An ordering solution for businesses, including user, delivery, and admin apps.',
    longDescription: 'A mobile app designed as an ordering solution for businesses, specifically an "Ecommerce order app." It is part of a multi-platform solution that includes a user app, a delivery app, and an admin app to manage the business.',
    category: 'Mobile App',
    imageUrl: 'https://res.cloudinary.com/cauders/image/upload/v1768683768/fajira-ecommerce_u3hbmk.png',
    technologies: ['Flutter', 'Dart', 'Firebase', 'Node.js'],
    gallery: [
        'https://res.cloudinary.com/cauders/image/upload/v1768683764/gallery-1_rjnbvd.pngg',
    ],
    featured: false,
    url: 'https://play.google.com/store/apps/details?id=com.fajira.ecommerce',
    industry: 'E-commerce',
    status: 'Live',
    year: 2022,
    implementation: ['Mobile Dev', 'Backend'],
     mobileScreenshots: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683759/gallery-4_eodajq.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683761/gallery-2_zzwyjo.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683760/gallery-3_ll5hwg.png',
    ]
  },
  {
    id: 15,
    slug: 'portia-fabrics',
    title: 'Portia Fabrics',
    description: 'An online store for Pakistani designer brand fabrics.',
    longDescription: 'An online store that provides Pakistani designer brand fabrics, dresses, and outfits. They specialize in a wide range of products including shawls, laces, and bridal couture, with a focus on quality, customer service, and unique selections. The website serves as a worldwide fashion store.',
    category: 'Web App',
    imageUrl: '/images/portfolio/portia-fabrics.png',
    technologies: ['Shopify', 'eCommerce', 'Liquid', 'Payment Gateway Integration'],
    gallery: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683725/gallery-1_mxfd5n.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683721/gallery-2_b3vnth.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683716/gallery-3_qfbpx5.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683725/gallery-4_cu3wbp.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683717/gallery-5_aneogz.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683718/gallery-6_utmynx.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683719/gallery-7_uhqf4u.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683719/gallery-8_fce4nx.png',
    ],
    featured: false,
    url: 'https://www.portia.pk/',
    industry: 'Fashion',
    status: 'Live',
    year: 2019,
    implementation: ['eCommerce Dev', 'Branding'],
  },
  {
    id: 16,
    slug: 'direct-coops',
    title: 'Direct Co-ops',
    description: 'A group-buying platform for small businesses.',
    longDescription: 'A group-buying platform and marketplace for small and medium-sized businesses and co-ops. It allows local independent businesses to leverage their group buying power to achieve better prices and compete with larger chains and online retailers.',
    category: 'Web App',
    imageUrl: '/images/portfolio/direct-coops.png',
    technologies: ['React', 'Node.js', 'Marketplace', 'E-commerce'],
    gallery: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683793/gallery-1_fxuizc.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683793/gallery-1_fxuizc.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683792/gallery-3_bndx83.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683794/gallery-4_vldlnv.png',
    ],
    featured: false,
    url: 'https://www.directcoops.com/',
    industry: 'B2B Marketplace',
    status: 'Live',
    year: 2020,
    implementation: ['Platform Dev', 'Strategy'],
  },
  {
    id: 17,
    slug: 'domene-no',
    title: 'Domene.no',
    description: 'A domain registration and web hosting service.',
    longDescription: 'Domene.no is a leading provider of domain registration and web hosting services in Norway. It offers a wide range of services for individuals and businesses to establish and maintain their online presence.',
    category: 'Web App',
    imageUrl: '/images/portfolio/domene-no.jpg',
    gallery: [
      'https://res.cloudinary.com/cauders/image/upload/v1768683783/gallery-1_l5wqp3.jpg',
      'https://res.cloudinary.com/cauders/image/upload/v1768683789/gallery-2_ybpnra.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683784/gallery-3_yglcla.png',
      'https://res.cloudinary.com/cauders/image/upload/v1768683785/gallery-4_xzowdf.png',
    ],
    featured: false,
    url: 'https://www.domene.no/',
    industry: 'Web Services',
    status: 'Live',
    year: 2018,
    implementation: ['Backend', 'Infrastructure'],
  }
];

export const featuredProjects = projects.filter((project) => project.featured);

export const projectCategories = ['All', ...Array.from(new Set(projects.map(p => p.category)))];

    
    